random_state : 42

data: 
  text_col: sentence
  label_col: sentiment
  text_col_original: text
model:
  # Logistic Regression hyperparameters
  C: 2.0
  penalty: l2
  solver: saga
  max_iter: 1000
  random_state: 42
  n_jobs: -1                     # Use all cores for training

mlflow:
  registered_model_name: sentiment-predictor

output:
  metrics_file: metrics.json
  model_file: pipeline.joblib
  confusion_matrix_file: confusion_matrix.csv